name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
version: VERSION
<<<<<<< HEAD
core: 8.x
=======
>>>>>>> dev
configure: config.sync
