/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

Drupal.debounce = function (func, wait, immediate) {
<<<<<<< HEAD
  var timeout = void 0;
  var result = void 0;
  return function () {
    for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
=======
  var timeout;
  var result;
  return function () {
    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
>>>>>>> dev
      args[_key] = arguments[_key];
    }

    var context = this;
<<<<<<< HEAD
    var later = function later() {
      timeout = null;
=======

    var later = function later() {
      timeout = null;

>>>>>>> dev
      if (!immediate) {
        result = func.apply(context, args);
      }
    };
<<<<<<< HEAD
    var callNow = immediate && !timeout;
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
    if (callNow) {
      result = func.apply(context, args);
    }
=======

    var callNow = immediate && !timeout;
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);

    if (callNow) {
      result = func.apply(context, args);
    }

>>>>>>> dev
    return result;
  };
};