/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Backbone, Drupal) {
  Drupal.quickedit.AppModel = Backbone.Model.extend({
    defaults: {
      highlightedField: null,
<<<<<<< HEAD

      activeField: null,

=======
      activeField: null,
>>>>>>> dev
      activeModal: null
    }
  });
})(Backbone, Drupal);